include:
  - local: './ci/install-rkorapclient-ci.yml'

build-rkorapclient-on-stable:
  extends: .install-rkorapclient
  image: ubuntu:latest
  cache:
    key: rkorapclient-ubuntu-stable
    paths:
    - apt-cache/
    - ccache/
    - rlib/

build-rkorapclient-on-rolling:
  extends: .install-rkorapclient
  image: ubuntu:rolling
