include:
  - local: ci/install-rkorapclient-ci.yml

build-rkorapclient-on-stable:
  extends: .install-rkorapclient
  image: rocker/tidyverse
  cache:
    key: rkorapclient-ubuntu-stable
    paths:
    - apt-cache/
    - ccache/
    - rlib/
  script:
    - start_section testing "Testing RKorAPClient"
    - echo -e "apt-cache\nccache\nrlib" >> .Rbuildignore
    - R -q -e "devtools::check(args = c('--no-examples'))"
    - R -q -e 'devtools::test()'
    - end_section testing

