include:
  - local: ci/install-rkorapclient-ci.yml

build-rkorapclient-on-stable:
  extends: .install-rkorapclient
  image: ubuntu:latest
  cache:
    key: rkorapclient-ubuntu-stable
    paths:
    - apt-cache/
    - ccache/
    - rlib/
  script:
    - start_section testing "Testing RKorAPClient"
    - R -q -e 'library(RKorAPClient); testthat::test_dir("tests/testthat")'
    - end_section testing

