coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
        base: auto
        branches:
          - master
          - main
        informational: true
    patch:
      default:
        target: auto
        threshold: 0.5%
        base: auto
        informational: true
